name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    container: condaforge/mambaforge:latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Test with Pydantic V1
      run: |
        apt update && apt install -y git make

        make env
        mamba install --name pydantic-units "pydantic <2"

        make test

    - name: Test with Pydantic V2
      run: |
        apt update && apt install -y git make

        make env

        make lint
        make test

        make docs

    - name: CodeCov
      uses: codecov/codecov-action@v4.1.1
      with:
        file: ./coverage.xml
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
